fix: remove `isLastAuthor` validation
storyblok/custom-app-examples pull request #22
Opened 2023-08-25 11:50 UTC by demetriusfeijoo

Ticket: EXT-1935
fixes #21

## What

Since for every newly created space, a default story is added automatically (home) and for this story, no `last_author` is provided, some adjustments were required to make it optional in our starter examples and does not break the page.

![Screenshot 2023-08-25 at 08 38 27](https://github.com/storyblok/custom-app-examples/assets/1240591/067b9b36-0a9e-40fc-9a5e-ce7d81bcd7ae)

![Screenshot 2023-08-25 at 08 37 51](https://github.com/storyblok/custom-app-examples/assets/1240591/4794422f-9194-452b-8e79-95bcb390439b)

2023-08-25 12:27 UTC, eunjae-lee commented on app-nextjs-starter/src/Story.ts
> +  'last_author' in data
What's the default value of last_author here? Is it empty string or undefined? If undefined, this condition will fail, right?

2023-08-25 12:28 UTC, eunjae-lee requested changes
This PR looks overall. I've left one question, and also the CI is broken. Could you take a look?

2023-08-25 17:31 UTC, demetriusfeijoo commented on app-nextjs-starter/src/Story.ts
> +  'last_author' in data
Hey @eunjae-lee, thanks for your question. 

The default value for `last_author` is `null`.

![Screenshot 2023-08-25 at 14 23 48](https://github.com/storyblok/custom-app-examples/assets/1240591/a2f47e3e-d2b3-4689-9b74-53f89fc7e20b)

2023-08-25 17:32 UTC, demetriusfeijoo commented
@eunjae-lee, the CI broking was something related to the action itself, I guess... I just rerun it and worked 😅.

2023-08-28 08:55 UTC, eunjae-lee commented on app-nextjs-starter/src/Story.ts
> +  'last_author' in data
ahh... it's `null`. I think this condition may give false impression that `last_author` exists in the data. What if we remove the condition at all?

2023-08-28 14:00 UTC, demetriusfeijoo commented on app-nextjs-starter/src/Story.ts
> +  'last_author' in data
I think the `last_author` property indeed exists inside the data, although it doesn't have any defined value. 

This condition validates the schema somehow so, I don't think it would be bad to have it.

However, as you felt this way, maybe others also feel the same, so I'm going to remove it. 😜

2023-08-28 14:12 UTC, demetriusfeijoo commented on app-nextjs-starter/src/Story.ts
> +  'last_author' in data
Validation removed @eunjae-lee.

2023-08-29 09:24 UTC, eunjae-lee commented
I've updated the description to follow this format. Now, once this pull request gets merged, the linked issue will automatically be closed as well.
https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue

2023-08-29 09:25 UTC, eunjae-lee approved these changes
looks good to me!

2023-08-29 09:33 UTC, demetriusfeijoo commented
Thanks for the review and also linking the issue @eunjae-lee 🙌

2023-08-29 09:33 UTC, merged