fix: upgrade version to manage authentication in US
storyblok/custom-app-examples pull request #6
Opened 2023-05-18 18:57 UTC by johannes-lindgren

Issue: EXT-1541

2023-05-19 09:49 UTC, eunjae-lee commented
Not sure if this PR is ready for review (because it says it's a draft PR). Ping me when you think it's ready (and also when it passes the CI)

2023-05-23 12:58 UTC, eunjae-lee requested changes

2023-05-23 12:58 UTC, eunjae-lee commented on app-nextjs-starter/pages/api/stories.ts
> +  )
With this, `fetchStories` will always resolve but I saw a code like

```js
  useEffect(() => {
    fetchStories(props.spaceId, props.userId)
      .then(stories => setStories(stories))
  }, [props.spaceId, props.userId])
```

then that `stories` might be either real `stories` or `error`. I guess you meant to print out error and return undefined or something like that?

2023-05-23 18:59 UTC, johannes-lindgren commented on app-nextjs-starter/pages/api/stories.ts
> +  )
It's a different `fetchStories`... one is for the client and the other for the server.

2023-05-24 09:04 UTC, eunjae-lee commented on app-nextjs-starter/pages/api/stories.ts
> +  )
Ahah you're right. I see which pattern you used here (following up our conversation yesterday 🙂)

2023-05-24 09:04 UTC, eunjae-lee approved these changes

2023-05-25 08:34 UTC, merged